name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: configure  
      run: ./configure.sh --program-prefix=PREFIX
      
    - name: make
      run: make
    - name: sudo make install
      run: sudo make install
    - name: make training
      run: make training
    - name: sudo make training-install
      run: sudo make training-install
    - name: mkdir build
      run: mkdir build
    - name: cd build && cmake .. && make
      run: cd build && cmake .. && make
    - name: sudo make install
      run: sudo make install
