name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: sudo apt update && sudo apt upgrade -y && sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 asciidoc libnss3 xsltproc libleptonica-dev libxss1 libasound2 libxtst6 xauth xvfb libpango1.0-dev mc python3-dev python3-pip cmake autogen  make libtool -u -m -y -f
      run: ./autogen.sh
    - name: configure  
      run: ./configure --program-prefix=PREFIX
      
    - name: make
      run: make
    - name: sudo make install
      run: sudo make install
    - name: make training
      run: make training
    - name: sudo make training-install
      run: sudo make training-install
    - name: mkdir build
      run: mkdir build
    - name: cd build && cmake .. && make
      run: cd build && cmake .. && make
    - name: sudo make install
      run: sudo make install
